### ISSUE TITLE
 Warp mode does not stop in Why_I_Like_Demos - Part 2

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#419] opened 2018-09-09 08:00 UTC
Warp mode does not stop in Why_I_Like_Demos in the second step (press space).
[Why_I_Like_Demos.D64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2364063/Why_I_Like_Demos.D64.zip)

This is the step:
<img width="761" alt="schermata 2018-09-09 alle 09 58 08" src="https://user-images.githubusercontent.com/41686391/45262454-39193180-b417-11e8-9efa-99b63c97b5ec.png">

**Comment by dirkwhoffmann** [comment] 2018-09-09 10:07
Most likely a duplicate of #410. I'll look at it asap.

**Comment by dirkwhoffmann** [comment] 2018-09-21 20:58
Will be fixed in 2.6

**Closed by dirkwhoffmann** 2018-09-21 20:58 UTC
Labels: duplicate
