### ISSUE TITLE
Virtual keyboard: f2/f4/f6/f8 not working

### ISSUE THREAD

**Issue by ha24-1** [dirkwhoffmann/virtualc64#817] opened 2024-12-13 16:18 UTC
.. I discovered this issue on [web64](https://vc64web.github.io/#): 

all shifted f-keys are executed like non-shifted (f2 executed as SHIFT f1 remains functional f1). Same for f7/f8.
Same behavior on VirtualC64.app (5.01). Using real Mac-Keyboard there's nothing to complain... :-)

Best regards,
H.

**Comment by mithrendal** [comment] 2024-12-13 19:26
Hi @ha24-1 I just checked in vc64web. 

with symbolic mapping enabled

<img width="696" alt="image" src="https://github.com/user-attachments/assets/98571155-17c8-4df4-b2cd-bf6c7a601cb9" />

it seems to work fine.

if `symbolic mapping` is `disabled` you have to press yourself `F1`+`ShiftKey` to get the `F2`

and thats probably the bug you mentioned 

that when pressing F2 on the virtual or physical keyboard (with symbolic mapping off) you get as a result `F1` . Yes thats weird. I will change it. 

In the meantime you can enable symbolic mapping and it should fix it.
 
Did I understand you correctly ? or is it still something else?

**Comment by ha24-1** [comment] 2024-12-13 20:05
thank you for your reply - you understand right! I expect when pressing virtual f2-key the expected programmatic f2-function on C64 will be executed... 
(discovered it on www.forum64.de 's world-exclusive software PUPU - respectively using the level-editor for this incredible new game!)

And generally: I very appreciate your work! 
I hope my "real-life"-use of vc64web and VirtualC64.app will make both much better...

**Comment by dirkwhoffmann** [comment] 2024-12-14 09:37
> Same behavior on VirtualC64.app (5.01)

It's not a bug. The idea of positional key mapping is to establish a one-to-one mapping between physical Mac keys and physical C64 keys. Thus, I cannot map `Mac::F2` to `C64::SHIFT`+`C64::F1` as it violates the one-to-one semantics. 

Is there a reason why you switched from symbolic mapping (which is the default) to positional mapping? Maybe we can adjust the symbolic keymap to fit your needs.

**Comment by dirkwhoffmann** [comment] 2024-12-14 09:41
P.S.: Please keep on reporting bugs like this. It's often the subtle things that differentiate good from great.

**Comment by mithrendal** [comment] 2024-12-14 17:01
published a bugfix for [vc64web](https://vc64web.github.io) F2, F4, F6, F8 should be working now fine.

**Comment by ha24-1** [comment] 2024-12-14 18:17
> > Same behavior on VirtualC64.app (5.01)
> 
> It's not a bug. The idea of positional key mapping is to establish a one-to-one mapping between physical Mac keys and physical C64 keys. Thus, I cannot map `Mac::F2` to `C64::SHIFT`+`C64::F1` as it violates the one-to-one semantics.
> 
> Is there a reason why you switched from symbolic mapping (which is the default) to positional mapping? Maybe we can adjust the symbolic keymap to fit your needs.

... please find attached a screenshot: I'm using the virtual keyboard with mouse only to execute f2:
1. klick SHIFT (key f1 turns to f2)
2. klick f2
3. klick is recognized as f1 (as shown in C64-program).

For webC64 it works now as expected. 
![screenshot1](https://github.com/user-attachments/assets/6a43405c-b881-4c46-ad4e-52c92ebf2667)

**Comment by ha24-1** [comment] 2024-12-14 18:19
> published a bugfix for [vc64web](https://vc64web.github.io) F2, F4, F6, F8 should be working now fine.

yes, I can confirm it - after automatic update of webC64 it works as expected. Perfect, thank you so much!

**Comment by dirkwhoffmann** [comment] 2024-12-15 13:57
Did you press the Shift key with the right mouse button? The right button will keep the key down, whereas the left button releases it automatically.

<img width="677" alt="Bildschirmfoto 2024-12-15 um 14 55 56" src="https://github.com/user-attachments/assets/a6ad005e-e451-424d-8484-07a5dd28b96c" />

**Comment by ha24-1** [comment] 2024-12-16 05:55
> Did you press the Shift key with the right mouse button? The right button will keep the key down, whereas the left button releases it automatically.

no difference in behavior - doesn't matter if I press SHIFT with left or right mouse button first: 
the f-key's lettering turns to f2, Ieft-klick the f2-key on virtual keyboard ans the result is: program functionality of f1 :-)

no big problem, I'm always using the real keyboard and there's everything fine.

**Comment by dirkwhoffmann** [comment] 2024-12-16 11:19
Strange enough. Pressing the Shift key with the right mouse button is supposed to hold the key down, as you can see here:

![Bildschirmfoto 2024-12-16 um 12 11 50](https://github.com/user-attachments/assets/a5250e86-ff68-4428-9195-344671508b18)

It correctly reports ASCII 140 in [64 Doctor](https://csdb.dk/release/?id=80611).

**Comment by mithrendal** [comment] 2024-12-16 16:37
I tested F2, F4, F6, and F8 in virtualC64.app, and they all functioned perfectly.  

Initially, I encountered some difficulty when trying to test with only the left mouse button. It took a moment to grasp the mechanics, particularly the requirement to use the secondary mouse button (typically the right button for right-handed users).  

For example, to use F2, you need to first click SHIFT on the virtual keyboard with the secondary mouse button, then press F2. To hold F2 for an extended period, you should click it (similar to the SHIFT key) with the secondary mouse button. However, if you want to release F2 immediately after pressing it, use the left mouse button on F2.

**Comment by ha24-1** [comment] 2024-12-17 08:00
Thank you for co-testing!
Apart from this, that Leftbutton- and Rightbutton-Klick on SHIFT both turns lettering on "virtual f-key from "f1" to "f2" (so at first sight it seems to be  indifferent which mouse button I have to press for f2):  
it is still not working on Version 5.01 - BUT on 5.1b2 (240909) it does: so everything is fine! 
Many thanks for your support!

**Closed** 2024-12-17 10:26 UTC
