### ISSUE TITLE
ReSID audio broken when emulating MOS 8580 with "Emulate audio filter" enabled

### ISSUE THREAD

**Issue by vonmillhausen** [dirkwhoffmann/virtualc64#353] opened 2018-07-07 13:26 UTC
VirtualC64 2.2, macOS 10.13.5.

When choosing to emulate the MOS 8580 SID using the ReSID engine, if `Emulate audio filter` is enabled then the audio output is heavily corrupted - mostly silent, with bursts of static. Turning off `Emulate audio filter` gives clean audio output (without filter effects); switching to MOS 6581 gives clean audio output with or without `Emulate audio filter`. Changing the `Sampling method` option has no impact.

Tested with both "Reluge 101%" (https://csdb.dk/release/?id=156960) and "Plarp!" (https://csdb.dk/release/?id=163172). Note, from reading around this may be an issue with ReSID, and not necessarily with VirtualC64 per-se - I also get broken audio output in Vice 3.0 with a similar configuration (although there Reluge gives total silence with no static).

**Comment by dirkwhoffmann** [comment] 2018-07-07 13:35
I experienced the same thing, and my impression was that it is related to the sampling method. Thanks to your investigations, we now know that it's not. We should keep an eye on what the VICE team is doing. If they fix it in their emulator, I'll happy to adapt the fixes in VirtualC64. If the problem persists, we can revert to an older reSID version, but for now, I suggest, we live with this bug for a while.

**Comment by vonmillhausen** [comment] 2018-07-07 13:44
@dirkwhoffmann No problem! Also as a side note, thank you for continuing your work on VirtualC64 - it gets better and better with every release! For example, the "Reluge" demo I linked above didn't used to work in older versions, but started working just fine in 2.1. I'm actually preferring VirtualC64 on my Mac now as my go-to emulator, as the interface is a lot friendly than the 3.x Vice builds on macOS so far, and I like a lot of the extra features like the snapshot engine and inspector.

**Comment by Alessandro1970** [comment] 2018-07-17 15:17
There are news about vice team:
https://sourceforge.net/p/vice-emu/code/35258

**Comment by puleyo** [comment] 2018-07-31 07:02
Is there any news about it?
... for the use I make of it I do not find any problems with this version of audio at the moment ...

**Comment by Alessandro1970** [comment] 2018-12-21 13:30
Hugo, good news. Thank you ALL ! :smiley:

**Comment by mortinus** [comment] 2018-12-21 13:34
:smile:  :smile:  :smile:  :crossed_fingers:

**Comment by mortinus** [comment] 2018-12-21 13:36
...this means that we could have a new RESID engine in VirtualC64 **3.3** ?

**Comment by Alessandro1970** [comment] 2018-12-21 13:38
... :zipper_mouth_face:  Napoleon ! ... :zipper_mouth_face: 

:crossed_fingers:

**Comment by dirkwhoffmann** [comment] 2018-12-21 16:12
Mission complete. Sneaked into SourceForge, shamelessly grabbed all their code and went out. Didn't even say good bye 😎. 

I've already done some comparison. They did work on the reset behaviour, so there is a real chance that they fixed the bug we're talking about in this thread. 

<img width="1043" alt="screenshot 2018-12-21 at 15 59 51" src="https://user-images.githubusercontent.com/12561945/50349953-bd627100-053d-11e9-8f17-0422ab2f5f82.png">

They also changed some calculations, so the new version might sound different, too.

<img width="779" alt="screenshot 2018-12-21 at 16 01 05" src="https://user-images.githubusercontent.com/12561945/50349988-dec35d00-053d-11e9-8b93-d3e365e38d18.png">

Integrating the code was easy: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha6.zip

I tried the new reSID implementation with a couple of games. Switching between chip models on-the- fly worked fine in all cases. 

Sorry for releasing a new alpha every ten minutes, but the reSID stuff really had to be integrated asap.

**Comment by Alessandro1970** [comment] 2018-12-22 08:42
All these "alpha" and "beta" are really very welcome !!!
It works well for me, thank you

**Comment by dirkwhoffmann** [comment] 2018-12-27 11:57
Issue is not completely solved by the new reSID version.

To reproduce: 
1. Load Terminator 2 Judgement Day.
2. Switch SID model from 6581 to 8580.
3. Switch "Emulate audio filter" from off to on.

There is an issue with the 8580 chip in combination with audio filter emulation.

**Comment by dirkwhoffmann** [comment] 2018-12-27 17:04
Could some window user please check out the following version of "Defender of the Crown" in VICE until the hacker intro comes up?

[DEFEND1.D64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2712925/DEFEND1.D64.zip)

 It plays the theme from "The Boat". When using ReSID (model 65xx) in VirtualC64 with audio filtering enabled, the sound is weird. Without filtering, it's great. If it's the same in VICE, audio filter emulation might be broken. If it sounds good in VICE, then I screwed it up.

**Comment by UgoCaneFifone** [comment] 2018-12-28 06:06
Ok, Tonight I will try on a windows 7 pc...

**Comment by UgoCaneFifone** [comment] 2018-12-28 23:38
Yes, vicesc 3.3 resid filter emulation is bad for the two chip sid. Itworks well only without filter emulation.

**Comment by dirkwhoffmann** [comment] 2018-12-29 07:35
Thanks! So the reSID filter emulation is screwed up in the latest VICE release. As a workaround, we could disable the filter by default (until VICE 3.4 is released). 

Another (longer term) possibility would be to integrate David's SID implementation from Hoxs64 as a third selectable engine (FastSID, reSID, Hoxs64). David only emulates the 8580 though.

**Comment by Alessandro1970** [comment] 2018-12-29 09:02
Does David's SID implementation work so well ?

_I think that it would be better to disable  (no to remove, only deselect it) the filter by default (until VICE 3.4 is released)._

**Comment by dirkwhoffmann** [comment] 2018-12-30 13:37
Audio filter emulation is now disabled by default: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha8.zip

It has to be enabled explicitly by the user.

**Comment by puleyo** [comment] 2019-01-03 09:59
mmmm.....
Now, we can see what is thinking about GPZ:
https://sourceforge.net/p/vice-emu/bugs/1091/

**Comment by Alessandro1970** [comment] 2019-01-03 10:09
... I do not think Groepaz of Hitmen (group) will answer with good manners ... :-D
... it would have been better to wait in silence, probably ...

**Comment by dirkwhoffmann** [comment] 2019-01-03 10:34
Who is Groepaz and Hitmen??? I only remember He-Man from the 80th.

**Comment by Alessandro1970** [comment] 2019-01-03 10:36
he is, now, a member of the VICE team...
...but I do not think that he will understand well the #puleyo sentence...

**Comment by mortinus** [comment] 2019-01-03 12:53
I'll handle that...

**Comment by dirkwhoffmann** [comment] 2019-01-03 13:05
I never had contact to anybody in the VICE team except André Fachat who wrote portions of the CIA code. At that time, he helped me out a lot by pointing to some test cases I wasn't aware of. 

I'm not really familiar with what's going on in the hard core retro scene, but I hope it's not something like this 😀: 

https://www.youtube.com/watch?v=rH8ded_L1YE

**Comment by Alessandro1970** [comment] 2019-01-03 13:09
... worse, much worse ...
#puleyo and #mortinus ...
... I saw you in an old 70s movie ... Chief Inspector Clouseau and the Pink Panther ...

Hey !!! ...you're not kids anymore

![lapanterarosasfida1](https://user-images.githubusercontent.com/34916641/50639276-33fd6680-0f61-11e9-9a66-6d74a73002b4.jpg)

**Comment by UgoCaneFifone** [comment] 2019-01-03 13:17
[](https://i.pinimg.com/originals/e0/16/39/e016398c058e2796263179262951f538.gif)

**Comment by UgoCaneFifone** [comment] 2019-01-03 13:17
https://i.pinimg.com/originals/e0/16/39/e016398c058e2796263179262951f538.gif

**Comment by UgoCaneFifone** [comment] 2019-01-03 13:17
[https://i.pinimg.com/originals/e0/16/39/e016398c058e2796263179262951f538.gif](url)

**Comment by Alessandro1970** [comment] 2019-01-03 13:37
Probably the ReSID has many problems that need to be corrected ... no hurry ...

![untitled 2](https://user-images.githubusercontent.com/34916641/50640428-2518b300-0f65-11e9-9ec0-b766ee57b1da.png)

**Comment by Alessandro1970** [comment] 2019-01-03 21:31
Groepaz has explained...
What do you think about ?

**Comment by mrdudz** [comment] 2019-01-03 21:50
> I do not think Groepaz of Hitmen (group) will answer with good manners

thanks for the flowers :)

so, yes, there are some issues with resid. for the most part, the 8580 filter emulation has been rewritten (before it was just the same as the 6581 filter, which was wrong of course) and that naturally (and unfortunately) brought us some regressions. (the "samples are audible although they shouldnt be" bug is related to this, and the "crackling filters"). it shouldnt be *that* much of an issue though, and mostly sound ok anyway.

other issues are mostly just detail issues that probably dont matter a lot in practise - and most importantly they were always there. they shouldnt matter much for most people either :)

now when i read the original post it sounds to me like this is a completely unrelated and totally different - likely macOS specific - problem. ie even with the new (and slightly buggy) 8580 filters you should never get "the audio output is heavily corrupted - mostly silent, with bursts of static". if this is what you get with a recent resid, i'd like to hear a recording of it. you could also try fixing the "sanitizer issues" in the list above locally and see if that helps. or perhaps crank up the warning level when compiling and see if that shows anything suspicious. its well possible that there are bugs that only trigger in clang (ie macOS) and happen to work with gcc. (a log output of resid compilation with max. warning level would be interesting)

that said, when comparing with VICE, make sure to select the right SID - the default changed from 6581 to 8580 a while ago.

and when reporting bugs, please give us exact references, like here: https://sourceforge.net/p/vice-emu/bugs/1086/ - without that its hard to reproduce (or even fix) anything.

**Comment by UgoCaneFifone** [comment] 2019-01-04 06:15
This is one of the rare cases, by divine grace, that GPZ has responded calmly ... we should take it as a message from heaven ... :-)
GPZ said:
- all filter issues i am aware of are related to the new 8580 filters. the 6581 filters were not changed for a long time and are considered OK
- i listened to the tune with 6581 and filters and it sounds normal to me
judging from your last post, it seems you are not switching to 6581 - which means you play it with 8580. then it will sound wrong, because the tune is made for a 6581 :) 
---
So we:
1) should we select the C64 configuration by default and not the C64c, including also the filter emulation? (Everything should work with 6581 ON !?)
2) is it a problem to be attributed only to OSX?

**Comment by Alessandro1970** [comment] 2019-01-04 06:55
Ok.
This iussue from vonmillhausen was opened for this:
...switching to MOS 6581 gives clean audio output with or without Emulate audio filter...
If the ReSID works well with MOS6581 and filter On we should use this configuration by default (C64 PAL) and **close the iussue** ...

**Comment by mortinus** [comment] 2019-01-04 07:12
I think you're right, I tried now (with a good brioche) the VirtualC64 6581 + Filter Emu and it works well even with the Reluge / Plarp and Defend1.d64 intro demo.
So we should choose the c64 configuration PAL (6581 + filter) by default and close this iussue, when the new VICESC 3.4 arrives, we will be able to talk about it again.
Let's leave the Resid 8580 alone and close this issue

**Comment by Alessandro1970** [comment] 2019-01-04 07:21
It could be a problem with 6581+filter emulation on OSX. 
In VICESC I remember that 6581+filter works well but there is some problem in VirtualC64 probably.

GPZ said: i listened to the tune with 6581 and filters and it sounds normal to me (IN VICESC)

How do you hear defend1.d64 intro in VirtualC64 (6581+filter mode) ?

If it sounds good you may close the iussue ...or if it sounds bad there is a problem in VirtualC64...

**Comment by dirkwhoffmann** [comment] 2019-01-04 08:49
I don't really get the point of the recent discussion. To get it back on track, I try to briefly distill the facts (as I understood them):

1. With the latest reSID code, Defend1.d64 sounds weird in VirtualC64 if filters are enabled in C64II hardware config.
2. Alessandro and Ugo reported that it can be can be reproduced in VICE.
 
Hence, I conclude the following: 

1. With the Defender of the Crown hacker intro, we have a good test case with the potential to exhibit subtle bugs or subtle differences between the old and the new reSID filter.
2.It is not clear yet, if it's a bug. One hypothesis is that the game was designed to play well on computers with the old SID, only. 

Before answering question 2, it doesn't make sense to go for bug hunting. I guess somebody with "the real thing" has to play a round of Defender to find this out.

**Comment by mrdudz** [comment] 2019-01-04 09:04
ehrm, 
a) its not about defender of the crown, but about the "das boot" tune used in the crack intro. -> https://csdb.dk/sid/?id=213 (see "6581")
b) most older tunes are "designed" for the old (6581) SID. also the vast majority of game tunes (the classic games from 80s at least) was made on/for 6581. its easy to check by just looking at the respective HVSC entry, those are mostly correct by now.
c) its not a bug. 6581 and 8580 filters sound very different. you get the same differences by running those tunes on a real C64

**Comment by dirkwhoffmann** [comment] 2019-01-04 10:36
@mrdudz: Thank you for confirming that it's not a bug and for your longer explanation given above. 

@all: VirtualC64 seems to be in a good state at the moment, so I decided to release V3.3. ISEPIC support will be postponed to V3.4, because I have to wait for the logic board shipping from Canada.

**Comment by shauladeneb** [comment] 2019-01-04 11:40
VirtualC64 has reached a state of the art both as reliability and stability and robustness, probably in short it will be enough just to maintain the code to keep it updated to the possible and likely upsetting of mother Apple.
Since the maintenance will probably require less effort, so .....are **true** the news and rumors that Prof. Dr. Dirk W. Hoffmann will release an Amiga emulator for OSX as like as VirtualC64 ?

Happy New Year !!!

**Comment by UgoCaneFifone** [comment] 2019-01-04 11:45
**Prof. Dr. Dirk W. Hoffmann will release an Amiga emulator for OSX** ??? !!!
-----------------------------------------------------------------------------

Wow !!! Really ? Great !!! ...wonderful news !

**Comment by Alessandro1970** [comment] 2019-01-04 13:39
A distant dream that would implement an Amiga500 module in VirtualC64?
It would be enough to have the possibility to use **512 or 1024 kb RAM** and be able to choose between **kickstart 1.2 or 1.3** ... to have 99% compatibility and a routine to read formats at least at 4X ...! ... someone said "dreams are desires"? or the opposite?

**Comment by DaitarnIII** [comment] 2019-01-04 13:51
This is straordinary !!! We'll hope about it!

**Comment by Harlock70** [comment] 2019-01-04 14:04
It would be beautiful.
Yes, I remember that I changed the kickstart from 12. to 1.3 and sometimes I removed the 512k ram with a small program in the boot-sector of the disk to load all the games.
Defender of the Crown worked well with Chip Ram's Kick 1.3 and 1014k chip-ram while on the other hand, to make Barbarian of Psygnosis work it was necessary to put the Kick 1.2 whit the external-switch (custom switch).

**Comment by dirkwhoffmann** [comment] 2019-01-04 16:23
Because we already deviated a little from the original topic in this thread.... this is really cool stuff 😎:

http://scriptedamigaemulator.net/

**Comment by dirkwhoffmann** [comment] 2019-01-04 16:33
OK, this is only a mockup... how it could look like 🤔.

![defender](https://user-images.githubusercontent.com/12561945/50698805-43a2ab00-1046-11e9-8a2a-e5d69e65d857.png)

**Comment by dirkwhoffmann** [comment] 2019-01-04 16:49
It's running in Chrome 🥳 (needs the original Kickstart though): 

<img width="957" alt="screenshot 2019-01-04 at 17 45 28" src="https://user-images.githubusercontent.com/12561945/50699602-9bdaac80-1048-11e9-882b-4f8ec3b648fa.png">

**Comment by Alessandro1970** [comment] 2019-01-04 16:55
I like the image mockup...

**Comment by Alessandro1970** [comment] 2019-01-05 14:04
> Anice side effect of using the existing GUI is that all existing shaders (Pixel upscalers, CRT filters, etc.) cA nice side effect of using the existing GUI is that all existing shaders (Pixel up scaler, CRT filters, etc.) can be reused at no cost.an be reused at no cost.

Can Mouse emulation and joystick from the GUI reused for the Amiga ? 
In the dialog for default models before or after the c64 series could be inserted the Amiga confuguration ? Than after c64 Roms could be set the path for the kickstart 1.2/1.3

**Comment by Alessandro1970** [comment] 2019-01-05 14:07
.mmmm better a single tab windows for the Amiga configuration

**Comment by dirkwhoffmann** [comment] 2019-01-05 15:08
VirtualC64 with an Amiga core (if it ever becomes reality) has to be a stand-alone app. Since the VirtualC64 GUI and the VirtualC64 emulator core are decoupled completely (they communicate solely via an Objective-C proxy translating Swift to C++ and vice versa), the GUI can be reused without major 
modifications. This includes, e.g., all the joystick emulation key stuff (eventually, writing clean code (if it exists at all) pays off 😏). 

I'm currently stepping through SAE (the Javascript UAE) in Chrome to get a feeling of how complex the code is. I.e., I need to find out how the run loop is organised. VirtualC64 has cycle-based scheduler that runs each sub-component (CPU, VICII, CIAs, ...) for exactly one CPU cycle. This is not the right approach for the Amiga. For this machine, an event-based mechanism has to be implemented. Unfortunately, I'm already "pissedoff" a little from the UAE code, because, e.g., they use a variable with exactly this name. Somehow not my humor, i.e., when it comes down to variable names. 

Furthermore, they have at least three variables for storing (variants) of the program counter: pc, pc_p, and instruction_pc = 0. Sure thing, it's not rocket science to find out what these variables do, but either a meaningful variable name or a little code comment (the // or /* */ stuff 😏) would save external code reviewers like me tons of time.

**Comment by dirkwhoffmann** [comment] 2019-01-05 20:38
I'm closing this topic as the original topic was reSID and there is nothing to do right now. 

All AMIGA discussion can continue here:

https://github.com/dirkwhoffmann/vAMIGA

or here: 

https://gitq.com/dirkwhoffmann/vAMIGA

Let's see how far we can get ... 

<img width="131" alt="logo_small" src="https://user-images.githubusercontent.com/12561945/50728959-03205b80-1132-11e9-98b8-1bb75a7839d1.png">

**Closed by dirkwhoffmann** 2019-01-05 20:38 UTC
Labels: bug

**Comment by Tekl** [comment] 2020-02-12 16:10
@dirkwhoffmann Has this bug been fixed? I can't confirm it for v3.3.2 on macOS 10.15.3. I have to disable the filters to hear music.

**Comment by dirkwhoffmann** [comment] 2020-02-15 11:17
> Has this bug been fixed?

No, it's not yet fixed in VirtualC64. I still have to check if the bug is fixed in VICE 3.4, but I doubt it (somebody from the VICE team claimed it to be a feature if I remember correctly). In my opinion it is a bug, because an audio filter does what it is named for: it filters. A sound filter can never screw up an audio stream completely (which happens in reSID under certain circumstances).

**Comment by dirkwhoffmann** [comment] 2020-07-02 13:28
I wasn't able to reproduce the audio filter bug in v3.4. I think the latest reSID changes in VICE 3.4 fixed the issue.
