### ISSUE TITLE
Preferences in the "Media Files" section are not retained on subsequent reboots

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#493] opened 2018-12-23 09:21 UTC
Hi,
When this morning I reopened the VirtualC64 I realized that the command "Load" * ", 8.1:" was no longer executed and I found the following situation in the "Media Files" section:
<img width="639" alt="schermata 2018-12-23 alle 10 20 25" src="https://user-images.githubusercontent.com/34916641/50382299-7212a480-069c-11e9-8d1a-8735228849d0.png">
I suppose the VirtualC64 does not save these settings correctly.

**Comment by dirkwhoffmann** [comment] 2018-12-27 17:49
Strange enough. I had the same issue, but I can no longer reproduce it, at least not in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha7.zip

Anyway, there was another bug (the checkmark "Take a snapshot" was not saved properly) which should be fixed now.

**Comment by Alessandro1970** [comment] 2018-12-29 08:57
If I deselect "take snapshot..." than I close and reopen VirtualC64, the "take snapshot.." option, in reverse, is always on and not off.
<img width="632" alt="schermata 2018-12-29 alle 09 54 42" src="https://user-images.githubusercontent.com/34916641/50536003-2ce4eb80-0b50-11e9-9d2e-aad1b5233df9.png">

**Comment by mortinus** [comment] 2018-12-29 09:50
With alpha 7 "TAKE SNAPSHOT" flag does not work in the configuration panel, if removed it reappears after relaunch the app.

**Comment by dirkwhoffmann** [comment] 2018-12-30 13:34
I think I found the root cause. The problem is Apple's NSTextField class which only triggers the connected action function on hitting Return or Tab. If the user types something and presses OK afterwards (without acknowledging the typed stuff via Return or Tab), the action function is *not* triggered and the entered data lost. One can handle this with certain workaround which, I did, and one of the workarounds caused the problem.

I hope that it's finally fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha8.zip

The "Take Snapshot" checkmark bug should also be fixed. I've cleaned up the whole API for that, down to the core emulator code.

**Closed by dirkwhoffmann** 2018-12-30 13:34 UTC
Labels: V 3.3, bug
