### ISSUE TITLE
Unable to invoke the ⬅︎ (to the left of the 1)

### ISSUE THREAD

**Issue by belucid** [dirkwhoffmann/virtualc64#205] opened 2015-09-06 22:05 UTC
I'm using Durex Forth in Virtual C64 and it includes a vi clone which uses the ⬅︎ key, to the left of the 1 key on the C64 keyboard, as the mode switch key (like ESC in vi).

Positionally, it'd be the ~ / ` key just to the left of the 1 key on a modern keyboard.

But the ~ key doesn't seem to do anything, with or without shift, and I don't see the ⬅︎ key in the Virtual C64 Keyboard menu. Is it mapped to some other key? FWIW I'm on a US MacBook Pro keyboard.

How is this key meant to be invoked? Thanks!

<img width="414" alt="keyboard_standard" src="https://cloud.githubusercontent.com/assets/12163/9706842/d00767be-54c1-11e5-9b42-5894622a31c9.png">

**Comment by dirkwhoffmann** [comment] 2015-09-07 07:50
I figured out what the problem is. On US keyboards, the upper left key ('~') has keycode 32. On European  keyboards, keycode 32 ist assigned to '<'. I have put together an experimental release which can be downloaded here: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_1.0rc3b.zip

Can you give it a try? (It doesn't show up as a software update because I am not able to test it on my own machine). 

Please also test, if '<' and '>' can still be typed on US keyboards. 

Best,
Dirk

**Comment by belucid** [comment] 2015-09-07 11:03
Dirk,

It worked like a charm! The ⬅︎ key works and < and > still work as well.

Thanks for the fast response and quick build. I'm back to hacking some 8-bit Forth!

Cheers,
Sean

**Closed** 2015-09-07 14:37 UTC
