### ISSUE TITLE
Crash on Exit

### ISSUE THREAD

**Issue by dmotowylak** [dirkwhoffmann/virtualc64#561] opened 2020-03-24 13:08 UTC
Hi, I really love VirtualC64, so easy and friendly to use. I wanted to report an issue to see if it is a verified bug. 
I find most of the time, after assigning a (bluetooth) joystick and pressing a joystick button for the first time, I get this crash message:
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [10478]

If I launch the program again, it will then work. 
I think it may have started when upgrading to OS X 10.5.
Is this a known issue?

**Comment by dirkwhoffmann** [comment] 2020-03-25 16:26
It's an unknown bug. Unfortunately, there is not enough information to debug it. 

Are you familiar with Xcode? If so, it would be great if you could reproduce the problem with a debug build of the latest code revision on the main branch. Xcode would tell us exactly where the emulator crashes.

**Comment by dirkwhoffmann** [comment] 2020-09-16 14:25
I'll close this because v4.0 has a very different internal architecture.

**Closed by dirkwhoffmann** 2020-09-16 14:25 UTC
Labels: bug
