### ISSUE TITLE
VirtualC64 crashes with Kaktus (1983)

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/virtualc64#787] opened 2024-03-04 20:25 UTC
After loading and run the game, Virtual C64 hangs in about 5 seconds.
[Kaktus (1983)(Supersoft).zip](https://github.com/dirkwhoffmann/virtualc64/files/14486788/Kaktus.1983.Supersoft.zip)

**Comment by dirkwhoffmann** [comment] 2024-03-04 21:31
Strange. I can't reproduce it. I made it to level 2 before I died: 

<img width="918" alt="Bildschirmfoto 2024-03-04 um 22 28 38" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/ef424593-e055-4863-b9c5-20fe42844e13">

**Comment by mithrendal** [comment] 2024-03-04 21:34
@Gianmarco72 which version number of Virtualc64 did you use ?

**Comment by dirkwhoffmann** [comment] 2024-05-30 10:00
I still haven't been able to reproduce it on my machine. 

I'll close this issue, hoping it's fixed in v5.0b1. Please reopen if not.

**Closed by dirkwhoffmann** 2024-05-30 10:00 UTC
