### ISSUE TITLE
Wish: Quit VirtualC64 without prompting

### ISSUE THREAD

**Issue by discmix** [dirkwhoffmann/virtualc64#577] opened 2020-07-28 10:27 UTC
Hi Dirk, 

it's not a problem, it's more a wish. 

I'm using VirtualC64 on my Mac and I'm learning a little assembler. Here I start VirtualC64 from the IDE and then close the VirtualC64 again. It happens very often. Now when closing the question comes up again and again: Save changes? 

Is it possible to set a default here in the options so that it really closes (without prompting) when the program is closed?

Thank you and regards
Marco

**Comment by dirkwhoffmann** [comment] 2020-07-28 11:39
There is already an option for it, but I've just seen that it doesn't work in all cases.

<img width="897" alt="Bildschirmfoto 2020-07-28 um 13 34 33" src="https://user-images.githubusercontent.com/12561945/88660613-5ae93380-d0d7-11ea-85bc-8d6ad1f560eb.png">

To make it work: 
- Enable the option.
- Quit and relaunch the emulator (the option should be still enabled and the emulator should no longer ask).

To reproduce the bug:
- Start the emulator with the option disabled.
- Enable it.
- Quit the emulator. The emulator will ask although it is not supposed to.

**Comment by discmix** [comment] 2020-07-28 13:38
Hi Dirk,

thank you so much for the fast response. I was blind! I just skipped this option!

Thanks and regards from a happy VirtualC64 User!!!
Marco

**Comment by dirkwhoffmann** [comment] 2020-07-28 13:40
I've reopened it (because of the bug 😉).

**Comment by dirkwhoffmann** [comment] 2020-09-01 13:29
I'll close this issue. The option will work as expected in v4.0.

**Closed by dirkwhoffmann** 2020-09-01 13:29 UTC
Labels: bug
