### ISSUE TITLE
No Sound on VirtualC64

### ISSUE THREAD

**Issue by Groepi** [dirkwhoffmann/virtualc64#231] opened 2016-04-26 18:32 UTC
Hello,

Thanks a lot for a your great Retro-Emu App.
The Only Sound that I hear is the drive sound.

Mac OS X 10.11.5 Beta
Virtual C64 1.4.2 and 1.4.1

have You any Idea?

Kind regards

Martin Gröpler

**Comment by jimrogerz** [comment] 2016-12-24 18:15
Hey Groepi, try switching the SID chip model in the hardware setup if you have issues until the bug is fixed.

Closing this issue because I think it is a dupe of #228

**Comment by Groepi** [comment] 2016-12-25 10:50
This doesn't fixed the Problem. I also you diffrent Kernel, this also do not solve the Problem. Any further Ideas?

**Comment by jimrogerz** [comment] 2016-12-25 18:40
Oh this is about the drive sound. No, I'm not sure about this. Disk seek sound works for me.

**Comment by dirkwhoffmann** [comment] 2017-06-16 09:42
The next release of VirtualC64 will contain a reimplemented Audio IO device (implemented in Swift using AudioToolbox instead of CoreAudio). I just merged in the new code into the master branch. Because I am not able to reproduce the sound problem on my Mac, I am not sure if this fixes the issue, but there is a big chance that it will (code is completely different).

**Comment by dirkwhoffmann** [comment] 2017-06-17 11:00
Version 1.5 is out.  I'm closing this issue in the hope that it is fixed. Please reopen if bug is still there.

**Closed by dirkwhoffmann** 2017-06-17 11:00 UTC
