### ISSUE TITLE
PC64-native files (*.P00...) fail by listing the directory

### ISSUE THREAD

**Issue by Gonzales555** [dirkwhoffmann/virtualc64#769] opened 2023-09-09 13:48 UTC
Hello Dirk,

First thank you for your fantastic work on VC64/VAmiga. The programs are very easy to handle and it's fun to use it. As I loaded some P00 files I saw that directory list was broken. In the documentation (https://petlibrary.tripod.com/PC64.HTM) they write on bytes $08-$17 is the Filename in PETSCII, padded with $00 not $A0 like D64 files. If I  changed the bytes of the file from $00 to $A0 it works fine. 

Best regards,
Gonzales

I have the Version 4.6 (230627)
 
![origin](https://github.com/dirkwhoffmann/virtualc64/assets/65393047/9ae01f0f-4299-45a9-9a77-e8857907b20a)
![changed](https://github.com/dirkwhoffmann/virtualc64/assets/65393047/8739c4c0-7d5f-4780-9cd6-18d043e81ec6)

**Comment by dirkwhoffmann** [comment] 2024-01-21 16:32
Will be fixed in v4.7. Thanks for reporting and for pointing out the root cause. 

v4.6: 

<img width="945" alt="Bildschirmfoto 2024-01-21 um 17 28 11" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/7b5713f0-0a1f-4356-b4c5-a2f64d8c66a2">

dev branch: 

<img width="959" alt="Bildschirmfoto 2024-01-21 um 17 28 30" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/29febd1b-36f2-4717-ae98-7523194e5c79">

**Comment by dirkwhoffmann** [comment] 2024-01-25 16:57
Fixed in v4.7b1

**Closed by dirkwhoffmann** 2024-01-25 16:57 UTC
Labels: bug, v4.7
