### ISSUE TITLE
some bugs ...

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#628] opened 2021-01-23 20:41 UTC
I am integrating the most recent core into vc64web and discovered some bugs...

most likely copy paste bugs...

### Bug1:
```

bool
TAPFile::isCompatibleName(const std::string &name)
{
    auto s = suffix(name);
    return s == "tap" || s == "TAP" || s == "t64" || s == "T64";
}


t64 and T64 are wrong conditions

```
### Bug2:

```
bool
Snapshot::isCompatibleName(const std::string &name)
{
    return true; // name == "VC64"; 
}
```
true is wrong condition change it to suffix(name) == "VC64" and "vc64"

### Bug3: taking a snapshot in vc64web

this code of vc64web
```
  Snapshot *snapshot = wrapper->c64->latestUserSnapshot(); //wrapper->c64->userSnapshot(nr);

  size_t size = snapshot->writeToBuffer(NULL);
  uint8_t *buffer = new uint8_t[size];
  snapshot->writeToBuffer(buffer);

  sprintf(wasm_pull_user_snapshot_file_json_result, "{\"address\":%lu, \"size\": %lu, \"width\": %u, \"height\":%u }",
  (unsigned long)buffer, 
  size,
  snapshot->header()->screenshot.width,
  snapshot->header()->screenshot.height
  );
  printf("return => %s\n",wasm_pull_user_snapshot_file_json_result);
  return wasm_pull_user_snapshot_file_json_result;

```

results in now in
Assertion failed: buf, at: Emulator/Files/AnyFile.cpp,155,writeToBuffer

before it worked. I think it comes from the   `size_t size = snapshot->writeToBuffer(NULL);` which is a bit weird and only for detecting the size for the buffer .... 

I found this as a replacement ... snapshot->size 

with this replacement no assertion failing while taking snapshot ...

but when viewing the saved snapshot it looks like this ...
![grafik](https://user-images.githubusercontent.com/17108995/105614829-45c23880-5dcc-11eb-86a6-c5fca4f513cb.png)

on javascript side the complete snapshot is filled with 0. 
in the meantime I checked also the C wrapper side ... 

```
  Snapshot *snapshot = wrapper->c64->latestUserSnapshot(); 
  size_t size = snapshot->size; //writeToBuffer(NULL);
  uint8_t *buffer = new uint8_t[size];
  snapshot->writeToBuffer(buffer);
  for(int i=0; i < 30; i++)
  {
    printf("%d",buffer[i]);
  }
  printf("\n");  
```

prints out only 00000000000000

**Comment by dirkwhoffmann** [comment] 2021-01-24 08:15
> Bug 1

This one is not a bug. There are some TAP files out there named T64. Fortunately, TAP and T64 files contain magic bytes. Hence, for distinguishing these formats, the input stream has to be checked with `isCompatibleStream`. The old code wasn’t very good though, because you had to check for TAP files first. This is because TAP file start with `C64-TAPE` and T64 files start with `C64<something>`. The new code (dev branch) takes care of this: 

```C++
bool
T64File::isCompatibleStream(std::istream &stream)
{
    const u8 magicT64[] = { 'C', '6', '4' };
    const u8 magicTAP[] = { 'C', '6', '4', '-', 'T', 'A', 'P', 'E' };

    if (streamLength(stream) < 0x40) return false;
    
    // T64 files must begin with "C64" and must not begin with "C64-TAPE"
    return
    !matchingStreamHeader(stream, magicTAP, sizeof(magicTAP)) &&
    matchingStreamHeader(stream, magicT64, sizeof(magicT64));
}

```

> Bug 2

This is a feature. Since snapshots contain magic bytes, there is no need to rely on a specific file name. However, it’s also fine with me if we require a specific suffix (again).

There was a bug though. Function ` isCompatibleName` was not called in make:

It's fixed on the dev branch. I’ve changed 

```C++
template <class T> static T *make(const char *path) throws
    {
        std::ifstream stream(path);
        if (!stream.is_open()) throw VC64Error(ERROR_FILE_NOT_FOUND);
        return make <T> (stream);
    }

```
to that:

```C++
    template <class T> static T *make(const string &path) throws
    {
        if (!T::isCompatibleName(path)) throw VC64Error(ERROR_FILE_TYPE_MISMATCH);
        
        std::ifstream stream(path);
        if (!stream.is_open()) throw VC64Error(ERROR_FILE_NOT_FOUND);
        return make <T> (stream);
    }
```

> Bug 3

I'll look into it...

**Comment by dirkwhoffmann** [comment] 2021-01-24 08:24
> Bug 3

Yes, `writeToBuffer(NULL)` is no longer supported as `size` can tell you reliably how big the snapshot is (the old implementation did a test run to determine the size).

How big is `size` in your test case?

**Comment by mithrendal** [comment] 2021-01-24 08:32
```
wasm_pull_user_snapshot_file 
000000000000000000000000000000 
return => {"address":33273496, "size": 2185900, "width": 384, "height":284 } 
wrote app with id=c64 - start screen vc64_storage.js:60:17
wrote snapshot with id=178 vc64_storage.js:75:17
Transaction is complete
```

**Comment by dirkwhoffmann** [comment] 2021-01-28 18:51
Can this one be closed?

**Closed** 2021-02-04 09:46 UTC
Labels: V 4.0, bug
