### ISSUE TITLE
Crash on restored snapshot with attached REU 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#812] opened 2024-09-24 06:16 UTC
How to reproduce

Start virtualC64.app v5.1 b2, versions before worked flawless

Attach REU 512K

Load something which accesses REU

Save snapshot

Restore snapshot

—> now the restored snapshot has capacity of 0Kb 😬

Game on … when game accesses the REU virtualC64 exists with a crash

**Comment by dirkwhoffmann** [comment] 2024-09-24 14:30
The issue is solved. Fix is on the dev branch.

**Comment by dirkwhoffmann** [comment] 2024-12-26 15:10
Fixed in v5.1

**Closed by dirkwhoffmann** 2024-12-26 15:10 UTC
Labels: bug, v5.1
