### ISSUE TITLE
WICO Joystick button when running

### ISSUE THREAD

**Issue by adamesq** [dirkwhoffmann/virtualc64#354] opened 2018-07-08 04:53 UTC
I'm having an issue with WICO Command Control Joysticks. This may be related to the 9 pin to USB converter, but I've never experienced the issue on any other emulator. When running left or right, the fire button triggers at the same iteration over and over until running stops. I have noticed if I trigger the fire button while running, the problem starts until I stop using the joystick for a second.

**Comment by adamesq** [comment] 2018-07-08 18:21
A little more details. I just tried an N64 controller (using an N64 to USB adapter, of course). It has the same issue. I'm using Bruce Lee as an example. When running left or right, the fire button triggers along with the side to side running. This DOES NOT happen with the analog stick. Also, with the DPad, Bruce keeps on running after letting go. This does not happen when using a standard 9 pin joystick (only the repetitive fire trigger).

**Comment by adamesq** [comment] 2018-07-09 18:18
Sure, Dirk! Thank YOU for all your work on the project! I've used Frodo and Power64. This one seems to be the best so far. I purchased the 9 pin converter about 15 years ago. I *think* it's this one: https://www.retronicdesign.com/en/home/ I've never seen this issue with recurring mouse clicking on another emulator.

**Comment by dirkwhoffmann** [comment] 2018-08-02 06:29
I just verified that the emulator is working correctly with an original Competition Pro II connected via a RetroFun USB adapter. I don't think the issue is related to the WICO joystick, because the old joysticks do not have any electronics inside. They simply connect electrical lines. I therefore expect the retro design adapter to be the culprit. Unfortunately, I only own two retro adapters. One is called aJoy and the other one is the RetroFun adapter mentioned above. I bought both on eBay. I didn't find the retronic design adapter on ebay or amazon though. It seems like they only sell it through their Canadian online store.

**Comment by adamesq** [comment] 2018-08-16 19:46
Thank you, Dirk. I remember reading about ajoy. Do both of those adapters work for you? I’d hunt one down on ebay if they do.

**Comment by dirkwhoffmann** [comment] 2018-08-17 05:43
Yes, both adapters work with my old Competition Pro II Joysticks. At least I didn't notice any issues with them playing Fort Apocalypse and Juice.

**Comment by dirkwhoffmann** [comment] 2018-08-28 08:26
I close this issue for now and open it again as soon as I have a WICO adapter at hand.

**Closed by dirkwhoffmann** 2018-08-28 08:26 UTC
Labels: bug
