### ISSUE TITLE
Toolbar and disk inserted

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#358] opened 2018-07-15 08:26 UTC
If I eject a disk (from the drop down menu "Eject") and  I press the reset button on the toolbar ("Power") the name of the inserted disk remains on the bar even if the disk is not there anymore.
The toolbar does not refresh itself after a disk or tape change.
So if I put a new and different disk always remains the name of the old disk.

<img width="781" alt="schermata 2018-07-15 alle 10 20 40" src="https://user-images.githubusercontent.com/34916641/42732021-53d73a1e-8819-11e8-87b7-4638bb57104d.png">

**Comment by dirkwhoffmann** [comment] 2018-07-16 06:29
The problem is that the D64 file should NOT be displayed in the title bar, because VirtualC64's native file format (document based app) are snapshot files only. Showing a D64 file name in the title bar suggests that choosing "Save" would write to the D64 file which never happens. 

I'll change it the following way:

A title will appears in the title bar only if a snapshot file was loaded or if the emulator has been saved to such snapshot file before.
All other windows will be made "Untitled" by default. 

I agree that the current behavior is quite confusing for the user.

**Comment by dirkwhoffmann** [comment] 2018-07-22 15:14
(Presumably) fixed in 2.3 beta 3 

http://www.dirkwhoffmann.de/virtualC64/VirtualC64_2.3_beta3.zip

**Closed by dirkwhoffmann** 2018-07-22 15:14 UTC
Labels: V2.3, bug
