### ISSUE TITLE
Can VirtualC64 / vAmiga be ported to Linux?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#537] opened 2019-10-09 10:42 UTC
**Linux Mint** is great (than Mac Os which comes from BSD)!

Linux Mint is free and OpenGL were not deprecated !

**WOW for VirtualC64 with the virtual Keyboard under LINUX**, that would be a Great Dream ! 
Now Mac Os is not Macintosh and in the future the MBP will be like an iPAD ....the time of Linux is come !

_Is difficult to port VirtualC64 on Linux ?_

...maybe porting the orrible Metal (c) to Vulkan under Linux

_Originally posted by @PakkunKinoppi in https://github.com/dirkwhoffmann/virtualc64/issues/536#issuecomment-539899506_

**Comment by PakkunKinoppi** [comment] 2019-10-09 11:08
Great. Wonderful !
Yes, It will be a great idea to have VirtualC64 and vAmiga under Linux !

**Comment by Alessandro1970** [comment] 2019-10-09 11:12
Hello to all,
Thanks for the new dedicated discussion.

Yes, I am in favor of starting the adventure of the beloved VirtualC64 and vAmiga under Linux.

I also think, as someone else, that Linux is closer to our "being Europeans".

Apple is no longer Macintosh "friendly", I also have keyboard problems, even the batteries of home iPhones are falling apart after each update ...

I conclude:
I am in favor of porting the beloved VirtualC64 and vAmiga under Linux.

Trusting a secret:
... now I'm downloading Linux Mint Cinnamon 64bit now!
![Untitled 2](https://user-images.githubusercontent.com/34916641/66476637-6ad74e80-ea96-11e9-8cba-886fdcb8c642.png)

**Comment by puleyo2000** [comment] 2019-10-09 11:19
Hi to all,
watching here from today waiting for VirtualC64 and VAmiga on LINUX !

Great emulator, right choose to follow Linux !

Bye

**Comment by rossimariolee** [comment] 2019-10-09 11:24
Goodmorning everyone !!!

This is news!

**Of course ! Yes  !**
**### Virtualc64 and vAmiga on Linux Mint!
Great idea!**

I have been using Mint Cinnamon for a year with Libreoffice and it's great!

**Comment by shaulaXX** [comment] 2019-10-09 11:38
Hi

I'm watching by now!
Off course waiting for VirtualC64 ported on Linux Mint, great !

Thank you if this conversion wiil be done !

...there isn't future for expensive apple, european minds have to work free together !
Long Life for Linux and for the very good emulator VirtualC64 !
Thank you again !
Bye Bye

**Comment by UgoCaneFifone** [comment] 2019-10-09 11:53
HI !
eheheh

### I come back to you now at the turn of the tide

Yes, VirtualC64 and vAmiga on Linux !

I'll follow you

**Comment by DaitarnIII** [comment] 2019-10-09 12:02
Here I am friends !

**But certainly, I am also in favor of bringing VirtualC64 on Linux.**

I don't want to take anything away from those who are fond of the Mac, I also have a Mac ... **but I'll never buy them again**. They are no longer the Macs of the past. It's like wanting to buy an Amiga with the PowerPC ... it's not an Amiga!

**I'm European too and Linux is our pride.**

**But yes! Long live VirtualC64 and vAmiga on Linux**

Post scriptum: I use Linux Mint too

**Comment by mortinus1967** [comment] 2019-10-09 12:23
_But where do you think you're going without me?_

Yes, yes, I also use linux ubuntu and it is much better, I don't really think to buy for me a MBP of € 2000,00,  half broken and full of problems when with 600 € I can buy a great laptop with twice the memory and double-space SSD !
I have a minitower with Ubuntu, but I'm also downloading Linux Mint, I've seen your photos today and I like this Cinnamon version.
... I don't give up on VirtualC64, I like it a lot, but I don't feel like paying Trump anymore ...
The VirtualC64 and the VAmiga on Linux are fine!

I follow you as always! ...on linux !

**Comment by Alvarez81** [comment] 2019-10-09 12:43
Hello
All these notifications have arrived to me and I have run to see what news on the old-dear VirtualC64.
I haven't had a Mac for months, the MBP screen broke and I have no guarantee, 
I'm not going to spend € 2,500.00 for a 128GB SSD with 8GB ram.
So I bought an Acer € 550.00 with 256gbSSD and 8GBRam, it works well, no problem !

I had my nephew put the great Linux Mint and unfortunately I'm using VICESC, **don't beat me**.

But now that **there is this hope** to revive the VirtualC64, _how nice!_
I follow you and I hope to be able to use Virtual on my Acer with Linux Mint!

_Hi #Alessandro1970 , you too the Mint?
The Mac now is no longer what it was 10 years ago and Apple doesn't like computer anymore!_

**Comment by dirkwhoffmann** [comment] 2019-10-09 12:43
Sorry, I shouldn’t have opened this thread without posting immediately. Mainly I opened it up to explain and discuss the reasons that make a Linux version of VirtualC64 unlikely to happen.

The short answer to the question whether VirtualC64 can be ported to Linux is "Yes and No". The long answer: Both VirtualC64 and vAmiga consist of three separate parts:

- The core emulator written in C++.
- The GUI written in Swift.
- An Objective-C bridge (Swift cannot talk to C++ directly, only to C).

Porting the core emulator would be a no-brainer. Although I don’t expect the emulator to compile out of the box, I expect that all issues could be ruled out in a day or so.

Porting the Swift code is the problem, because it's just not possible. The GUI had to be implemented completely from scratch (including all GPU shaders etc.). Looking back, I spent about half of the development time on the GUI and I would have to spend the same amount of time on the Linux GUI. I simply don't have enough spare time to do this. 

Implementing just a rudimentary GUI wouldn't help either, because the GUI is the strong side of VirtualC64. Loosing this unique selling point would degrade it to just another emulator. Since VICE has better compatibility, it simply wouldn't make much sense to have VirtualC64 around as another emulator.

I'm sorry if I raised unrealistic expectations by opening this thread.

Nevertheless I am also eager to check out Linux Mint Cinnamon in general. I haven't used Linux for quite some time and I am curious how it has evolved over the years.

**Comment by Alessandro1970** [comment] 2019-10-09 12:59
Hi @Alvarez81 
The problem is twofold:
on the one hand Apple seems to be directed towards the iPhone and iPad, diminishing, so it seems to me, the work on computers (well known that Woz is out and unfortunately Steve is no more), in my part they would say that Apple is just a machine for money rate without substance and without ideas.
On the other hand, an MBP in my part will cost too much, really too much, and for what you pay for it, it has poor and obsolete hardware.
Linux will have some problems, I'm not a technician on the subject, I'm just a fan in my spare time, but I think Linux can give us so much that we come from Amiga and we are in fact mistreated by Apple.
The Linux Mint is so much stuff and free too!
Then everyone is free to think as they wish.

**Comment by dirkwhoffmann** [comment] 2019-10-09 13:30
> I'm using VICESC

😲 @Alvarez81 How dare you? 

(Just kidding)

For me, this discussion is quite interesting. Seems like Apple is loosing its fan base. Good to know that I am not the only one who is disappointed about their latest products.

**Comment by Alessandro1970** [comment] 2019-10-10 10:49
Hello to all,
installed on MBP Linux Mint ...
1) FacetimeHD CAM not recognized there is no "really" compatible driver [patjak / bcwc_pcie / driver does'n work on suspend and has poor quality; hard to install] - Cheese app works but bad resolution with that driver.
2) Apple mouse -> horrible, compatible pc USB mouse mmmm in short
3) after an hour on LINUX the MBP is hot, scary! Optimized as on the web ... a little better ... you can cook meat or hot dogs on it
4) Retina screen ok but not very fast graphics as optimized on MBP [no such driver for Intel IRIS]
5) SSD was not easy but it works fairly well
6) I don't like ViceSc on Linux nor Windows ...
7) Problems with the fans are always active, found remedy on the web ... they don't turn on anymore! Panic
8) Adventure on LINUX ended

Dear friends ... my next computer will be an MBP with Arm CPU

Bye

**Comment by dirkwhoffmann** [comment] 2019-10-10 11:45
> my next computer will be an MBP with Arm CPU

Thanks for reporting. This saves me a ton of time. Seems like the situation with Linux is the same as it was 10 years ago. Great for servers, not for desktops.

BTW, I still like the A500 😆. Good to have four of them in my office now. Just in case ...

**Comment by Alessandro1970** [comment] 2019-10-10 11:50
Still waiting for gotek, it seems to be arrived at Milan

**Comment by UgoCaneFifone** [comment] 2019-10-10 12:04
Ok, so just downloading Catalina... 
You can close this issue becouse the issue is linux at this point...

...but that Mach5 crt support ? Any news about it is an old thread.

**Closed** 2019-10-14 06:01 UTC
Labels: question
