### ISSUE TITLE
v4.01 Keysets - Freezing Emulation

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#658] opened 2021-03-28 22:06 UTC
https://csdb.dk/release/?id=202171

I am finding similar games like the one above that using keysets as a joystick and holding down the keys up and left direction freezes the emulation. Same also happens in v3.4 as well....

**Comment by dirkwhoffmann** [comment] 2021-05-05 17:09
Findings: The games freezes when CUR DOWN + CUR LEFT are pressed simultaneously, but this has nothing to do with joystick emulation. It also happens if keyset 2 is assigned to the joystick, or if no keyset is assigned at all. If I haven't overseen anything, it's not a bug.

**Closed** 2021-05-06 11:36 UTC
Labels: invalid
