### ISSUE TITLE
OMIUC demo, flicker and graphic errors when Pyramid appears

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#557] opened 2020-03-08 10:13 UTC
OMIUC demo, flicker and grapic errors when Pyramid appears

[Omiuc_1.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/4303065/Omiuc_1.d64.zip)
[Omiuc_2.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/4303066/Omiuc_2.d64.zip)

VirtualC64:
<img width="713" alt="Schermata 2020-03-08 alle 11 08 36" src="https://user-images.githubusercontent.com/34916641/76160832-c719c980-612d-11ea-9d86-bb4b9ea8ce0a.png">

ViceSC:
<img width="708" alt="Schermata 2020-03-08 alle 11 10 59" src="https://user-images.githubusercontent.com/34916641/76160838-d00a9b00-612d-11ea-9f21-91e8a6d4e1a3.png">

**Comment by rossimariolee** [comment] 2020-04-14 08:05
Yes, I tryed this demo and it doesn't work. There is any possibility to download an updated version of VirtualC64, some time has passed before last update... 😢    ...my cat too 😿   ...Ugo too I think 😭

**Comment by dirkwhoffmann** [comment] 2020-04-14 08:16
> some time has passed before last update... 😢

True, but there hasn't been much progress in the meantime 🙄. 

> my cat too 😿

What happened to your cat?

**Comment by rossimariolee** [comment] 2020-04-14 08:37
...my cat uses to play with your great VirtualC64 too !
VirtualC64 is a legend ...a must !
Thanks

**Comment by Alessandro1970** [comment] 2020-04-26 16:51
...what kind of problem could be this graphic error ?
I tryed different configurations of Vic and cpu but always failed

**Comment by rossimariolee** [comment] 2020-05-19 06:53
Good Morning.

Please, could you update VirtualC64 ?

**Comment by rossimariolee** [comment] 2021-02-12 09:18
Hi Dirk
Are there any news for this demo? Have you found what the bug is?
Greetings to all of you.

**Comment by PakkunKinoppi** [comment] 2021-02-18 12:39
Hi, none configuration let this demo working. The problem is probably something in vic timing, I think.
In HOXS64 it works but I haven't find anything about this demo on the web; Krestages are ok in VirtualC64 and they are more complex.. I'm very courious about this bug.

**Comment by dirkwhoffmann** [comment] 2021-02-18 12:46
I am also curious about this bug, but it doesn't make sense to debug specific demos at the moment. What has to be done is a rerun of all VICE emulator tests in VirtualC64, because they haven't been run for a longer time now. It may also be a good time to think about test automatization again.

**Comment by Alessandro1970** [comment] 2021-02-18 12:50
Hi
Wow !
_test automatization again_

Interesting, very interesting !
...waiting for results !

:crossed_fingers:

**Comment by Haroldo64** [comment] 2021-04-27 06:02
...following

**Comment by emoon** [comment] 2021-04-27 06:18
@Haroldo64 just a tip: You don't actually need to write something on the issue to follow it, you can just press `subscribe` on the the issue (which is on the right lower corner at the top of the issue)

**Comment by dirkwhoffmann** [comment] 2021-05-11 06:51
Update: Still broken in v4.1

**Comment by dirkwhoffmann** [comment] 2021-05-15 14:33
My recent VICII changes seem to have fixed this issue:

<img width="919" alt="Bildschirmfoto 2021-05-15 um 16 20 00" src="https://user-images.githubusercontent.com/12561945/118364981-17df4a80-b59b-11eb-9657-0bfe1630776c.png">

**Comment by Alessandro1970** [comment] 2021-05-16 07:35
Omiuc demo works well in 4.1 release, you can close this issue for me.

**Comment by dirkwhoffmann** [comment] 2021-05-16 07:44
> Omiuc demo works well in 4.1 release, you can close this issue for me.

Confirmed, it got fixed with 4.1. My comment "Still broken in v4.1" is wrong. I guess I accidentally tested it in 4.0.1 instead of 4.1 when I wrote that comment.

**Closed by dirkwhoffmann** 2021-05-16 07:44 UTC
Labels: bug, demo
