### ISSUE TITLE
1581 and REU support

### ISSUE THREAD

**Issue by Vweber73** [dirkwhoffmann/virtualc64#729] opened 2022-05-06 20:22 UTC
Hi,
Any plan to support 1581 disks and REU memory expansion ? That would be great for GEOS, as well as support for 1351 mouse...
Not talking about C128 support ! :)

Thanks and cheers

**Comment by dirkwhoffmann** [comment] 2022-05-07 11:35
Duplicate of #706 and #710.

> Any plan to support 1581 disks and REU memory expansion ?

Maybe eventually... Right now I am stuck in a pile of other work.

**Closed by dirkwhoffmann** 2022-05-07 11:35 UTC
Labels: duplicate

**Comment by Vweber73** [comment] 2022-05-07 12:00
Ok, thanks !
