### ISSUE TITLE
NTSC version seems to have timing issue

### ISSUE THREAD

**Issue by mpkincai** [dirkwhoffmann/virtualc64#754] opened 2023-01-25 17:23 UTC
First of all, thank you for this great piece of software, I love using it.

Logistics:
Kernal: Jiffydos 6.01
1541:  Jiffydos 6.0
VIC:  6567, 8562 fps = native, Emulate grey dot bug checked (I tried both of these)
CIAs:  MOS 6526, emulate timer B bug checked
Power Supply:  50Hz stable, 60Hz stable
SID:  8580
Logic Board:  Glue = Discrete
Ram Pattern: Vice
Software Version (I tested on both of these):  4.5.1, installed via brew.  4.6b1, downloaded from the website

PC:  Apple M1 Pro, Ventura 13.0.1

I've seen this on a couple of titles now (Lester was the other) however I will reference lady pac for this example (https://lowcarb.itch.io/lady-pac-pc-version).  When moving the pacman around, the pacman will jump ahead or lag/jump from time to time.  I do not see this problem running the same program in PAL mode or when running on vice in NTSC mode.  I do not have a real NTSC machine available to test with but if helpful I can switch a MKII over to NTSC to test on.

Let me know if there are any logs or other debugging information that would be helpful.

**Comment by dirkwhoffmann** [comment] 2023-03-30 09:39
NTSC emulation in VirtualC64 is less accurate than PAL emulation. There are a couple of failing VICE tests, but I've never been in the mood to fix them because most title support PAL anyway. 

However, I've not been able to reproduce the "jumps" when running LadyPac in NTSC mode.

**Comment by dirkwhoffmann** [comment] 2024-01-21 16:44
I'll close this one for the time being as NTSC compatibility is known to be inferior to PAL compatibility. 

The next straightforward step would be to crawl through all NTSC VICE tests and fix them one after another. This is nothing I'd like to spend my time on at the moment, as I always run the emulator in PAL mode.

**Closed by dirkwhoffmann** 2024-01-21 16:44 UTC
Labels: wontfix
