### ISSUE TITLE
4.0b5 Keyboard Issues still not fixed.

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#635] opened 2021-02-04 18:38 UTC
https://user-images.githubusercontent.com/31462938/106939508-5b016600-66ee-11eb-8d40-090e841152ed.mp4

1. Watch the video, I am trying to click SHIFT + ARROW UP and it moves the cursor down.
2. Same goes with SHIFT + ARROW LEFT

3. Also (Not a keyboard issue, just regular operations) moving the cursor up while joystick keys in port 2 is on should work as per real hardware testing.

Please look....

**Comment by dirkwhoffmann** [comment] 2021-02-06 16:22
The virtual keyboard issue is fixed in v4.0. It was display bug: The key cap stayed red although the key was already released. Please make sure to use the right mouse key for Shift (which holds down the key). Otherwise Shift gets released the same time you release the mouse button. 

Regarding the other issue, I'll try to do some experiments with the C64 Maxi which must be somewhere around here...

**Comment by dirkwhoffmann** [comment] 2021-05-06 11:42
>  I'll try to do some experiments with the C64 Maxi which 

I've checked the interference caused by a joystick in port 1 and the keyboard matrix on the C64 maxi and everything looks fine to me. VirtualC64 behaves the same way.

**Closed by dirkwhoffmann** 2021-05-06 11:42 UTC
Labels: V 4.0, bug
