### ISSUE TITLE
EasyFlash Cartridge Support

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#429] opened 2018-09-27 10:02 UTC
Hi, as written by other friends I think it is more correct to open an issue for the support of this cartridge called EasyFlash.

Thank you
Bye

https://www.c64-wiki.com/wiki/EasyFlash
https://csdb.dk/release/?id=166110
![moduleasyflash](https://user-images.githubusercontent.com/41686391/46138830-4161d100-c24d-11e8-9a5d-b50d6fd62893.jpg)

**Comment by MrStargazer** [comment] 2018-09-27 13:32
I like this tooo !!!

**Comment by mithrendal** [comment] 2018-09-27 14:03
there are also loads of other cool EasyFlash Releases....
https://csdb.dk/release/?id=166861
https://csdb.dk/release/?id=165405
https://csdb.dk/release/?id=166168
https://csdb.dk/release/?id=167043
https://csdb.dk/release/?id=164883

but this year Excess released an enhanced and reworked speedball2 version (https://csdb.dk/release/?id=166110) which is outstanding. They back ported graphics and speach synthesis from the Amiga-Version and integrated that into the existing c64 version. They had solved a lot of difficulties to fit all that into the c64 memory.  Finally you can hear "ice cream"! EasyFlash Cartrige helped them as it could hold up to 1 Mb of data. 

I like to see support for that cartrige file too.

**Comment by mortinus** [comment] 2018-09-27 14:11
Uh! @mithrendal ...Great links!

**Comment by mithrendal** [comment] 2018-09-27 15:17
@Alessandro1970 yeah making these cartriges took time, but loading huge amounts of data and running from a easyflash .crt file is nearly instantly. I tried it out with Vice. With the use of the EF .crt format you could also develop and bypass the constrained amount of memory in the c64 by swapping and temporarily loading **massive amounts** of data lets say 32Kb in a second. Cool for new apps wich use a lot speach output ! See the releases on csdb.dk  many of them were just released in 2018.
For multidisk c64-apps with long loading times this cartrige format is a game changer, believe me !!!  ;-)

**Comment by dirkwhoffmann** [comment] 2018-09-28 07:27
This cartridge is more complicated than the others and requires a thorough familiarization with the details. I'd also like to see this cartridge supported, but please don't expect it soon.

**Comment by mortinus** [comment] 2018-10-15 09:35
...Has EasyFlash Cartridge **3** buttons ?!

![img_4276__14919 1336620171 1280 1280](https://user-images.githubusercontent.com/41686391/46942779-540e3f80-d06e-11e8-86fa-0f1e321eb07b.JPG)

**Comment by Alessandro1970** [comment] 2018-10-15 14:42
**EasyFlash 3 buttons**
The EF3 cartridge has three buttons; MENU, SPECIAL and RESET:

MENU -button 
    _always resets into the EF3 menu. The operation of the other two buttons is case sensitive._

SPECIAL -button
    _In EF3 menu, it exits to BASIC (without deactivating the cartridge)._
    _In EasyFlash mode, it exits to BASIC (leaving the selected EF slot active)._
    _In freezer cartridge mode, it acts as the Freeze -button of the selected cartridge._
    _Other modes: No operation._

RESET -button
    _In EasyFlash mode, resets the selected cartridge._
    _In freezer cartridge mode, acts as the Reset button of the selected cartridge._
    _In KERNAL cartridge mode, resets the machine leaving the selected KERNAL active._

**Comment by mithrendal** [comment] 2018-10-15 18:51
I don’t care about the emulation of the three buttons. I just want to load into the EF3 crt file...

**Comment by Alessandro1970** [comment] 2018-10-22 07:28
There is also an early but good version with only a butto and one switch: the push button on the top of the cartridge is for resetting while the two position switch is used when adding new content to the cart.
It has an 1 MB Flash memory which makes it possible to ‘burn’ data to the cartridge using the C64 as no EPROM programmer is needed.

![img_2941-600x800](https://user-images.githubusercontent.com/34916641/47281721-b1f5d680-d5dc-11e8-9bca-8de6b2205b9e.jpg)

**Comment by dirkwhoffmann** [comment] 2018-10-24 14:40
Support should be implemented in two stages:

1. Add support for pre-programmed cartridges.
There is a good explanation in EasyFlash-ProgRef.pdf.
http://skoe.de/easyflash/doku.php?id=develdocs 

2. Make ROMs programmable.
The EasyFlash cartridge uses flash memory of type AMD 29F040:
http://robotics.ee.uwa.edu.au/eyebot/doc/DataSheets/29F040.pdf

Stage 1 shouldn't be too difficult. Stage 2 might be more time-consuming.

**Comment by dirkwhoffmann** [comment] 2018-10-25 08:36
😎

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_EasyFlash.zip

<img width="970" alt="bildschirmfoto 2018-10-25 um 10 24 42" src="https://user-images.githubusercontent.com/12561945/47486844-8e7f9580-d841-11e8-8494-b2120e1ef9c2.png">

**Comment by dirkwhoffmann** [comment] 2018-10-25 08:53
"Finally you can hear 'ice cream'". How can I hear that in Speedball 2? 

Anyway, I lost 0:102 🤭.

<img width="970" alt="bildschirmfoto 2018-10-25 um 10 51 04" src="https://user-images.githubusercontent.com/12561945/47488175-1ebeda00-d844-11e8-8a35-0c5a57bf6831.png">

**Comment by Alessandro1970** [comment] 2018-10-25 08:59
rightly @mithrendal wrote here that the resources listed here (CSDB) without easyflash are not utilizable, just for this reason.
Otherwise I do not think anyone needs this cartridge to load programs or games faster (saving them on ROMs) since the emulator optimally handles the thing in another way; maybe nostalgic will appreciate anyway.

**Comment by Alessandro1970** [comment] 2018-10-25 09:36
@mortinus the EasyFlash is a revolutionary cartridge, I've never had it but you need it to be able to use at least for the C64-software that is on the net.
**have you tried the AR 7.5 cartridge?** ...instead the Stardos...
This cartridge (AR 7.5) has an exceptional fastload, works well with VirtualC64, has many options and commands for managing the disk drive that are very valid and effective:
![untitled 2](https://user-images.githubusercontent.com/34916641/47490824-d0acd500-d849-11e8-8f11-497aaf36d69f.jpg)

**Comment by mithrendal** [comment] 2018-10-25 19:10
Wow,
it really works. that is fantastic. How did you manage a 000-102 result ??? Thank you very much !!!
I am so happy.  That made my day !!!

I just played a very short session and could not see the ice cream cut scene either. 

but you can watch the Ice-cream cutscene for the c64 here ... so it should be in this version ...
https://www.youtube.com/watch?time_continue=12&v=ztuMxsb85CU

http://www.indieretronews.com/2018/05/speedball-2-ultimate-is-coming-to-c64.html#more

you can read some backgrounds  of the overhauled version and some comments about memory limits and why they cannot bring it on disk yet with all the extra image stuff in...
https://www.lemon64.com/forum/viewtopic.php?t=67867&start=0

**Comment by Alessandro1970** [comment] 2018-10-25 20:42
If I use these cartridge or i I load the same cartridge one after the other several times it hangs, or try several time to drag&drop the same crt on the virtualC64 screen:

[Error.zip](https://github.com/dirkwhoffmann/virtualc64/files/2516648/Error.zip)

[mmzmken.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2516649/mmzmken.crt.zip)
[Legacy+Legend-Saxxon.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2516650/Legacy%2BLegend-Saxxon.crt.zip)

**Comment by puleyo** [comment] 2018-10-26 06:00
Also to me some EasyFlash cartridges if put repeatedly or even once just crash the virtualc64

**Comment by Alessandro1970** [comment] 2018-10-26 21:18
Lastninja easyflash in VirtualC64 hangs if loaded more than one time (drag&drop):
[report.txt](https://github.com/dirkwhoffmann/virtualc64/files/2520945/report.txt)

<img width="979" alt="schermata 2018-10-26 alle 23 14 46" src="https://user-images.githubusercontent.com/34916641/47592853-5d07e680-d975-11e8-9b31-a58fca8ebcd0.png">

Cartridge: 
[The Last Ninja all in one Fix.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2520947/The.Last.Ninja.all.in.one.Fix.crt.zip)

**Comment by dirkwhoffmann** [comment] 2018-10-27 06:57
It's some memory handling issue: 

    VirtualC64(38583,0x1018ab5c0) malloc: Incorrect checksum for freed object 0x103890200: probably modified after being freed.

I'm not sure about the cause yet. it might be related to the issue that was posted a couple of weeks ago about a crash in high Sierra (I had closed the issue without a fix. Unfortunately, I can't find it in the database any more).

**Comment by Alessandro1970** [comment] 2018-10-27 08:38
the strange thing is that the virtualc64 hangs and closes itself only with some easyflas cartridges, not with all.
In fact, if I try with speedball it never occurs.
Could this be incompatibility with some cartridges?

**Comment by Alessandro1970** [comment] 2018-10-27 08:53
Can someone run this easyflash cartridge ?

[Lemmings_ef_(FINAL-100pc).zip](https://github.com/dirkwhoffmann/virtualc64/files/2521599/Lemmings_ef_.FINAL-100pc.zip)

**Comment by dirkwhoffmann** [comment] 2018-10-27 08:55
It crashes for cartridges with more than 64 chip packets. Embarrassing bug, do not wanna talk about it in detail 🙄. Uploading a fix in a minute ...

**Comment by dirkwhoffmann** [comment] 2018-10-27 08:59
http://www.dirkwhoffmann.de/virtualc64/VirtualC64_EasyFlash2.zip

Lemmings doesn't work though. Did you already check in VICE?

**Comment by dirkwhoffmann** [comment] 2018-10-27 12:30
OK, thanks, I look into it. Maybe, these CRTs use some of the special bank switching combinations that are declared as "invalid. don't use." in the EasyFlash hardware description. We'll see ...

**Comment by Alessandro1970** [comment] 2018-10-28 07:55
Also Flimbo's Quest EF hangs on VirtualC64
[FlimbosQuest.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2522574/FlimbosQuest.crt.zip)

<img width="554" alt="schermata 2018-10-28 alle 08 51 04" src="https://user-images.githubusercontent.com/34916641/47613407-2625f380-da8f-11e8-8d33-d45a08555528.png">
<img width="1162" alt="schermata 2018-10-28 alle 08 53 39" src="https://user-images.githubusercontent.com/34916641/47613408-31791f00-da8f-11e8-8b2e-015c52dcac68.png">

**Comment by Alessandro1970** [comment] 2018-10-28 08:11
Turrican on VirtualC64 hangs before loading menù
[Turrican.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2522582/Turrican.crt.zip)
<img width="1017" alt="schermata 2018-10-28 alle 09 09 40" src="https://user-images.githubusercontent.com/34916641/47613542-60909000-da91-11e8-91b0-d91a80f556e2.png">

**Comment by dirkwhoffmann** [comment] 2018-10-29 09:14
Interesting. At some point in the code, Lemmings writes a 7 into $DE02 which selects 16k game mode. This means that ROML is visible at $8000 and ROMH at $A000. Afterwards, it reads the values from $A000 and $A001 which should come from ROMH. In VirtualC64, the values 78 and A2 are returned which are the values inside the ROM chip. In VICE, 01 and A4 are read. 🤔

Need to find out where 01 and A4 are coming from ...

**Comment by dirkwhoffmann** [comment] 2018-10-29 10:00
Now it's clear what happens: 

In my log (which I created while running VICE), I found the line: 5023: flash040core_store(0555) AA

If you look at the following table in row "Autoselect", you'll see the values 01 A4 which I didn't know where they come from:

<img width="1044" alt="bildschirmfoto 2018-10-29 um 10 52 19" src="https://user-images.githubusercontent.com/12561945/47642491-111d9300-db69-11e8-8c88-9f2aca85d416.png">

To make a long story short: Lemmings (and presumably the other non-working cartridges) make use of the fact that EasyFlash cartridges contain FlashRoms of type 29F040. To make these games work, the flash Roms have to be emulated properly. I a going to implement it, but it'll take some time (need to read und understand the spec first).

**Comment by dirkwhoffmann** [comment] 2018-11-01 08:50
Lemmings turns out to be a valuable test case. Thanks for filing that!

Despite the fact that is reads the manufacture IDs from the FlashRom, it arranges the Rom data inside the CRT file in an unusual way. All EasyFlash .crts which I analyzed so far, mapped the even chip packets to ROML and the odd packages to ROMH. Lemmings is different (e.g., see package 110 and 111) : 

<img width="491" alt="bildschirmfoto 2018-11-01 um 09 43 01" src="https://user-images.githubusercontent.com/12561945/47841823-2b4eaf80-ddbb-11e8-970e-22980b6b35f5.png">

I'll have to modify the current EasyFlash CRT loader to copy with that (which isn't difficult though) ...

**Comment by dirkwhoffmann** [comment] 2018-11-01 13:39
Correction: EasyFlash seems to use Flash Roms of type Am29F040B, not Am29F040.

![easyflashpcb](https://user-images.githubusercontent.com/12561945/47855006-9dd38580-dde3-11e8-9812-3c5af55c2d03.jpg)

**Comment by dirkwhoffmann** [comment] 2018-11-01 15:41
😎

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_EasyFlash3.zip

<img width="970" alt="bildschirmfoto 2018-11-01 um 15 59 35" src="https://user-images.githubusercontent.com/12561945/47862165-c7e17380-ddf4-11e8-94c1-5a4724de596e.png">

**Comment by puleyo** [comment] 2018-11-04 09:44
Now all my Easyflash cartridges now work fine too.

**Comment by dirkwhoffmann** [comment] 2018-11-04 10:19
Fixed in 3.1 which is now online.

**Closed by dirkwhoffmann** 2018-11-04 10:19 UTC
Labels: Priority-Medium, V 3.1, enhancement
