### ISSUE TITLE
Normal foreground/background switching using dock icon not working.

### ISSUE THREAD

**Issue by tsupplis** [dirkwhoffmann/virtualc64#454] opened 2018-11-05 09:50 UTC
When virtualc64 is in the background, it sometimes does not work to bring the window in the foreground, the only way to switch back is to act on the overlapping window/application. Furthermore, the menu shows Force Quit, looking like the application is unresponsive.
This is reproducible 90% on Mojave after opening virtualc64 and loading a program from a floppy.

**Comment by dirkwhoffmann** [comment] 2018-11-05 10:50
I had this issue a couple of days ago, but I thought it happened because I was running the app in Xcode (Xcode sometimes causes strange effects in debug mode). Unfortunately, I didn't find a way to reproduce it deterministically on my machine. Could you do the following for me? Start VirtualC64 from the console, reproduce the issue, and dump the debug messages that came out in the console?
Maybe, that gives us a hint. Second question: Are you running the emulator with option "Pause while in background"? Maybe it's related to that option, too. (A locked semaphore or something like that would be typical for the symptom you're describing).

**Comment by dirkwhoffmann** [comment] 2018-11-05 12:45
Hmm, I still cannot reproduce it on my machine. However, I noticed that the emulator hangs in macOS 10.14 for a couple of seconds when a file dialog opens (e.g., when selecting "Insert Disk..." from the menu). In the log output, I can see a couple of error messages: 

2018-11-05 13:35:01.172637+0100 VirtualC64[19238:1447109] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=19238
2018-11-05 13:35:01.172948+0100 VirtualC64[19238:1447109] SecTaskCopyDebugDescription: VirtualC64[19238]/0#-1 LF=0
2018-11-05 13:35:12.324032+0100 VirtualC64[19238:1447145] [default] Unable to load Info.plist exceptions (eGPUOverrides)
objc[19238]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9b7671d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x6006b43eadc8). One of the two will be used. Which one is undefined.

Not sure if this is related to the problem. By googling a bit, I've seen that a lot of developers have similar messages in their logs, but I didn't find a site pointing to a solution. Some of the messages seem to be caused by Apple's own bugs.

**Comment by Alessandro1970** [comment] 2018-11-06 09:04
I tried several times, but it never hangs on my MBP (with or without the _pause while in background option_).

**Comment by dirkwhoffmann** [comment] 2018-11-08 12:52
I'm still not able to reproduce the problem (although I did experience it in the past). Could it be that it's fixed with macOS 10.14.1? tsupplis, did you run 10.14 or 10.14.1?

**Comment by tsupplis** [comment] 2018-11-08 12:58
Both. It seems fairly 'reproducible'. 
I have now downloaded the code, I will try to explore under debugger this week end, and I will test on older version of MacOS. (Which branch should I use?)
Can we keep the issue open for the time being?

**Comment by dirkwhoffmann** [comment] 2018-11-08 13:07
Thanks for looking into it! I'm frequently merging back to the master branch, so you can fork from there. Alternatively, you can fork from V3.1 which will be kept stable (only small bugfixes in case there is a need for a 3.1.2 version).

Sure, we keep this issue open.

**Comment by dirkwhoffmann** [comment] 2018-11-09 15:53
Just had a frozen emulator on my machine. I connected the Instruments Activity Monitor to the running program and got the following:

<img width="874" alt="bildschirmfoto 2018-11-09 um 16 47 18" src="https://user-images.githubusercontent.com/12561945/48272800-c5f46180-e43f-11e8-99e3-4a0bab1dd4e0.png">

I have no glue where the 1,7 GiB 😳 come from, but the issue might be related to memory allocation.

**Comment by puleyo** [comment] 2018-11-27 06:46
Good morning,
I saw that the version of the virtualc64 alpha10 is very stable and the tests that did not work before were adequate.
When will version 3.2 come out?

**Comment by dirkwhoffmann** [comment] 2018-11-29 11:44
Hi Puleyo. Yes, it might be a good time for releasing 3.2.
I'm unsure of the severity of the issue described in this thread though.

**Comment by Alessandro1970** [comment] 2018-11-29 12:04
Has I said on 6/11 I cannot succeed in reproducing this issue as described before. Could it be depend by other stuff installed on Mac OS ?

**Comment by dirkwhoffmann** [comment] 2018-11-30 15:51
V3.2 has been released. I close this issue for the time being. Please reopen if it should reoccur in 3.2.

**Closed by dirkwhoffmann** 2018-11-30 15:51 UTC
Labels: bug

**Comment by dirkwhoffmann** [comment] 2018-11-30 16:01
V3.2 seems to be a little faster than V3.1.1. 

In warp mode (C64-II), with all CRT effects off, I get: 

V3.1.1: 7.05 MHz 
V3.2: 7.95 MHz 

More than 10% faster 😎.
